### ISSUE TITLE
Crash with impactful 20.8.1 and Epic Fight 20.8.9 on trident ranged attack 

### ISSUE THREAD

**Issue by maximogta** [Cyber2049/Epic-Fight-Impactful#5]
Crashes with when trident ranged attack impacts on entity.
[crash-2024-08-15_13.00.45-server.txt](https://github.com/user-attachments/files/16624593/crash-2024-08-15_13.00.45-server.txt)

**Comment by qVoidreaver** [comment]
This bug happens with all types of ranged attacks

NOTE: With projectiles
